#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="$ROOT_DIR/deploy"
OUTPUT_DIR="$DEPLOY_DIR/output"
BUILD_DIR="$DEPLOY_DIR/.build"

if command -v git >/dev/null 2>&1; then
  GIT_SHORT_SHA="$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || true)"
else
  GIT_SHORT_SHA=""
fi

if [ -z "${CRM_VERSION:-}" ]; then
  if [ -n "$GIT_SHORT_SHA" ]; then
    CRM_VERSION="$(date +%Y%m%d%H%M%S)-$GIT_SHORT_SHA"
  else
    CRM_VERSION="$(date +%Y%m%d%H%M%S)"
  fi
fi

PACKAGE_NAME="intelligent-marketing-crm-$CRM_VERSION"
if [ -n "${CRM_PACKAGE_FILE_NAME:-}" ]; then
  PACKAGE_FILE_NAME="$CRM_PACKAGE_FILE_NAME"
else
  PACKAGE_BRANCH="${CRM_PACKAGE_BRANCH:-$CRM_VERSION}"
  PACKAGE_BRANCH="${PACKAGE_BRANCH#crm-}"
  PACKAGE_BRANCH="${PACKAGE_BRANCH%-[0-9]*}"
  PACKAGE_FILE_NAME="crm-$PACKAGE_BRANCH-release.tar.gz"
fi
if [[ "$PACKAGE_FILE_NAME" != *.tar.gz ]]; then
  PACKAGE_FILE_NAME="$PACKAGE_FILE_NAME.tar.gz"
fi
PACKAGE_DIR="$OUTPUT_DIR/$PACKAGE_NAME"
PACKAGE_ARCHIVE="$OUTPUT_DIR/$PACKAGE_FILE_NAME"
IMAGE_ARCHIVE="$PACKAGE_DIR/images/crm-images.tar"

random_text() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi
  date +%s%N | sha256sum | awk '{print $1}'
}

run_frontend_install() {
  cd "$ROOT_DIR/frontend"
  if [ -f package-lock.json ]; then
    npm ci
  else
    npm install
  fi
}

echo "开始构建智能营销管理系统离线包：$CRM_VERSION"

rm -rf "$BUILD_DIR" "$PACKAGE_DIR"
rm -f "$PACKAGE_ARCHIVE" "$PACKAGE_ARCHIVE.sha256"
mkdir -p "$BUILD_DIR/backend" "$BUILD_DIR/frontend" "$PACKAGE_DIR/images" "$PACKAGE_DIR/scripts" "$OUTPUT_DIR"

echo "构建后端 Jar"
cd "$ROOT_DIR/backend"
mvn -DskipTests clean package

BACKEND_JAR="$(find "$ROOT_DIR/backend/crm-web/target" -maxdepth 1 -name 'crm-web-*.jar' ! -name '*.original' | head -n 1)"
if [ -z "$BACKEND_JAR" ]; then
  echo "未找到后端 Jar：backend/crm-web/target/crm-web-*.jar"
  exit 1
fi

cp "$BACKEND_JAR" "$BUILD_DIR/backend/app.jar"
cp "$DEPLOY_DIR/docker/backend/Dockerfile" "$BUILD_DIR/backend/Dockerfile"

echo "构建前端 Dist"
run_frontend_install
npm run build

cp -R "$ROOT_DIR/frontend/dist" "$BUILD_DIR/frontend/dist"
cp "$DEPLOY_DIR/docker/frontend/Dockerfile" "$BUILD_DIR/frontend/Dockerfile"
cp "$DEPLOY_DIR/docker/frontend/nginx.conf" "$BUILD_DIR/frontend/nginx.conf"
cp "$DEPLOY_DIR/docker/frontend/write-runtime-config.sh" "$BUILD_DIR/frontend/write-runtime-config.sh"

echo "准备 Python AI Runtime"
mkdir -p "$BUILD_DIR/ai-runtime"
cp "$ROOT_DIR/crm-ai-runtime/requirements.txt" "$BUILD_DIR/ai-runtime/requirements.txt"
cp "$ROOT_DIR/crm-ai-runtime/Dockerfile" "$BUILD_DIR/ai-runtime/Dockerfile"
cp -R "$ROOT_DIR/crm-ai-runtime/app" "$BUILD_DIR/ai-runtime/app"

echo "构建 Docker 镜像"
docker build -t "crm-backend:$CRM_VERSION" "$BUILD_DIR/backend"
docker build -t "crm-frontend:$CRM_VERSION" "$BUILD_DIR/frontend"
docker build -t "crm-ai-runtime:$CRM_VERSION" "$BUILD_DIR/ai-runtime"

echo "准备中间件镜像"
docker image inspect postgres:16-alpine >/dev/null 2>&1 || docker pull postgres:16-alpine
docker image inspect redis:7-alpine >/dev/null 2>&1 || docker pull redis:7-alpine
docker image inspect minio/minio:latest >/dev/null 2>&1 || docker pull minio/minio:latest

echo "保存离线镜像"
docker save -o "$IMAGE_ARCHIVE" \
  "crm-backend:$CRM_VERSION" \
  "crm-frontend:$CRM_VERSION" \
  "crm-ai-runtime:$CRM_VERSION" \
  postgres:16-alpine \
  redis:7-alpine \
  minio/minio:latest

cp "$DEPLOY_DIR/docker-compose.yml" "$PACKAGE_DIR/docker-compose.yml"
cp "$DEPLOY_DIR/env.example" "$PACKAGE_DIR/env.example"
cp "$DEPLOY_DIR/scripts/deploy-offline.sh" "$PACKAGE_DIR/scripts/deploy-offline.sh"
cp "$DEPLOY_DIR/README.md" "$PACKAGE_DIR/README.md"
chmod +x "$PACKAGE_DIR/scripts/"*.sh

CRM_DB_PASSWORD_VALUE="${CRM_DB_PASSWORD:-$(random_text)}"
CRM_REDIS_PASSWORD_VALUE="${CRM_REDIS_PASSWORD:-$(random_text)}"
CRM_JWT_SECRET_VALUE="${CRM_JWT_SECRET:-$(random_text)}"

cat > "$PACKAGE_DIR/.env" <<EOF
CRM_VERSION=$CRM_VERSION
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-crm}
CRM_TIMEZONE=${CRM_TIMEZONE:-Asia/Shanghai}

CRM_FRONTEND_PORT=${CRM_FRONTEND_PORT:-80}
CRM_FRONTEND_API_BASE_URL=${CRM_FRONTEND_API_BASE_URL:-}
CRM_FRONTEND_API_TIMEOUT=${CRM_FRONTEND_API_TIMEOUT:-30000}
CRM_ASSISTANT_TYPEWRITER_INTERVAL=${CRM_ASSISTANT_TYPEWRITER_INTERVAL:-12}
CRM_ASSISTANT_TYPEWRITER_STEP=${CRM_ASSISTANT_TYPEWRITER_STEP:-4}

CRM_DB_NAME=${CRM_DB_NAME:-crm}
CRM_DB_USERNAME=${CRM_DB_USERNAME:-app_user}
CRM_DB_PASSWORD=$CRM_DB_PASSWORD_VALUE
CRM_JPA_DDL_AUTO=${CRM_JPA_DDL_AUTO:-update}

CRM_REDIS_ENABLED=${CRM_REDIS_ENABLED:-true}
CRM_REDIS_PASSWORD=$CRM_REDIS_PASSWORD_VALUE
CRM_REDIS_DATABASE=${CRM_REDIS_DATABASE:-1}

CRM_JAVA_OPTS=${CRM_JAVA_OPTS:--Xms512m -Xmx1024m -Dfile.encoding=UTF-8}
CRM_JWT_SECRET=$CRM_JWT_SECRET_VALUE
CRM_JWT_TTL_SECONDS=${CRM_JWT_TTL_SECONDS:-86400}
CRM_PASSWORD_RESET_EXPOSE_TOKEN=${CRM_PASSWORD_RESET_EXPOSE_TOKEN:-false}
CRM_LOG_LEVEL=${CRM_LOG_LEVEL:-INFO}
CRM_CHANNEL_UPLOAD_DIR=${CRM_CHANNEL_UPLOAD_DIR:-/app/uploads/channel}
CRM_STORAGE_UPLOAD_DIR=${CRM_STORAGE_UPLOAD_DIR:-/app/uploads}
CRM_STORAGE_PUBLIC_PATH=${CRM_STORAGE_PUBLIC_PATH:-/uploads}
CRM_AGENT_WEB_SEARCH_ENABLED=${CRM_AGENT_WEB_SEARCH_ENABLED:-false}
CRM_AGENT_WEB_SEARCH_PROVIDER=${CRM_AGENT_WEB_SEARCH_PROVIDER:-searxng}
CRM_AGENT_WEB_SEARCH_ENDPOINT=${CRM_AGENT_WEB_SEARCH_ENDPOINT:-}
CRM_AGENT_WEB_SEARCH_API_KEY=${CRM_AGENT_WEB_SEARCH_API_KEY:-}
CRM_AGENT_WEB_SEARCH_TIMEOUT_MS=${CRM_AGENT_WEB_SEARCH_TIMEOUT_MS:-8000}
CRM_AGENT_WEB_SEARCH_MAX_RESULTS=${CRM_AGENT_WEB_SEARCH_MAX_RESULTS:-5}
CRM_AGENT_WEB_SEARCH_FETCH_DETAIL=${CRM_AGENT_WEB_SEARCH_FETCH_DETAIL:-true}
CRM_AGENT_WEB_SEARCH_DETAIL_LIMIT=${CRM_AGENT_WEB_SEARCH_DETAIL_LIMIT:-3}
CRM_AI_INTERNAL_TOKEN=${CRM_AI_INTERNAL_TOKEN:-$(random_text)}
CRM_AI_RUNTIME_TIMEOUT_MS=${CRM_AI_RUNTIME_TIMEOUT_MS:-90000}
CRM_AI_LOG_LEVEL=${CRM_AI_LOG_LEVEL:-INFO}
CRM_AI_WEB_SEARCH_ENABLED=${CRM_AI_WEB_SEARCH_ENABLED:-false}
CRM_AI_WEB_SEARCH_PROVIDER=${CRM_AI_WEB_SEARCH_PROVIDER:-searxng}
CRM_AI_WEB_SEARCH_ENDPOINT=${CRM_AI_WEB_SEARCH_ENDPOINT:-}
CRM_AI_WEB_SEARCH_API_KEY=${CRM_AI_WEB_SEARCH_API_KEY:-}
CRM_AI_WEB_SEARCH_TIMEOUT_SECONDS=${CRM_AI_WEB_SEARCH_TIMEOUT_SECONDS:-8}
CRM_AI_WEB_SEARCH_MAX_RESULTS=${CRM_AI_WEB_SEARCH_MAX_RESULTS:-5}
CRM_AI_CHECKPOINT_ENABLED=${CRM_AI_CHECKPOINT_ENABLED:-false}
CRM_AI_CHECKPOINT_BACKEND=${CRM_AI_CHECKPOINT_BACKEND:-memory}
CRM_AI_CHECKPOINT_POSTGRES_URI=${CRM_AI_CHECKPOINT_POSTGRES_URI:-}
CRM_AI_CHECKPOINT_AUTO_SETUP=${CRM_AI_CHECKPOINT_AUTO_SETUP:-true}
CRM_AI_TRACE_CAPTURE_PAYLOAD=${CRM_AI_TRACE_CAPTURE_PAYLOAD:-false}
LANGSMITH_TRACING=${LANGSMITH_TRACING:-false}
LANGSMITH_API_KEY=${LANGSMITH_API_KEY:-}
LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-crm-ai-runtime}
LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT:-https://api.smith.langchain.com}
LANGSMITH_HIDE_INPUTS=${LANGSMITH_HIDE_INPUTS:-false}
LANGSMITH_HIDE_OUTPUTS=${LANGSMITH_HIDE_OUTPUTS:-false}
LANGGRAPH_STRICT_MSGPACK=${LANGGRAPH_STRICT_MSGPACK:-true}

CRM_NACOS_ENABLED=${CRM_NACOS_ENABLED:-false}
CRM_MINIO_ENABLED=${CRM_MINIO_ENABLED:-false}
CRM_MINIO_ENDPOINT=${CRM_MINIO_ENDPOINT:-http://crm-minio:9000}
CRM_MINIO_PUBLIC_URL=${CRM_MINIO_PUBLIC_URL:-/minio}
CRM_MINIO_ACCESS_KEY=${CRM_MINIO_ACCESS_KEY:-minioadmin}
CRM_MINIO_SECRET_KEY=${CRM_MINIO_SECRET_KEY:-$(random_text)}
CRM_MINIO_BUCKET=${CRM_MINIO_BUCKET:-crm}
CRM_MINIO_PUBLIC_READ=${CRM_MINIO_PUBLIC_READ:-true}
CRM_ES_ENABLED=${CRM_ES_ENABLED:-true}
CRM_ES_URIS=${CRM_ES_URIS:-http://crm-elasticsearch:9200}
CRM_ES_USERNAME=${CRM_ES_USERNAME:-}
CRM_ES_PASSWORD=${CRM_ES_PASSWORD:-}
CRM_KB_INGEST_CORE_SIZE=${CRM_KB_INGEST_CORE_SIZE:-2}
CRM_KB_INGEST_MAX_SIZE=${CRM_KB_INGEST_MAX_SIZE:-4}
CRM_KB_INGEST_QUEUE_CAPACITY=${CRM_KB_INGEST_QUEUE_CAPACITY:-100}
CRM_KB_CHUNK_MAX_CHARS=${CRM_KB_CHUNK_MAX_CHARS:-900}
CRM_KB_CHUNK_OVERLAP_CHARS=${CRM_KB_CHUNK_OVERLAP_CHARS:-120}
CRM_KB_EMBEDDING_ENABLED=${CRM_KB_EMBEDDING_ENABLED:-true}
CRM_KB_EMBEDDING_BASE_URL=${CRM_KB_EMBEDDING_BASE_URL:-http://host.docker.internal:11434/v1}
CRM_KB_EMBEDDING_API_KEY=${CRM_KB_EMBEDDING_API_KEY:-}
CRM_KB_EMBEDDING_MODEL=${CRM_KB_EMBEDDING_MODEL:-bge-m3:latest}
CRM_KB_EMBEDDING_DIMENSIONS=${CRM_KB_EMBEDDING_DIMENSIONS:-0}
CRM_KB_EMBEDDING_TIMEOUT_MS=${CRM_KB_EMBEDDING_TIMEOUT_MS:-30000}
CRM_KB_ES_INDEX=${CRM_KB_ES_INDEX:-crm_knowledge_chunk}
CRM_KB_ES_TIMEOUT_MS=${CRM_KB_ES_TIMEOUT_MS:-10000}
CRM_KB_MILVUS_ENABLED=${CRM_KB_MILVUS_ENABLED:-true}
CRM_KB_MILVUS_ENDPOINT=${CRM_KB_MILVUS_ENDPOINT:-http://crm-milvus:19530}
CRM_KB_MILVUS_TOKEN=${CRM_KB_MILVUS_TOKEN:-}
CRM_KB_MILVUS_DATABASE=${CRM_KB_MILVUS_DATABASE:-}
CRM_KB_MILVUS_COLLECTION=${CRM_KB_MILVUS_COLLECTION:-crm_knowledge_chunk}
CRM_KB_MILVUS_TIMEOUT_MS=${CRM_KB_MILVUS_TIMEOUT_MS:-10000}
EOF

cat > "$PACKAGE_DIR/VERSION" <<EOF
CRM_VERSION=$CRM_VERSION
BUILD_TIME=$(date '+%Y-%m-%d %H:%M:%S')
GIT_SHORT_SHA=$GIT_SHORT_SHA
EOF

echo "压缩离线包"
cd "$OUTPUT_DIR"
tar -czf "$PACKAGE_FILE_NAME" "$PACKAGE_NAME"

if command -v sha256sum >/dev/null 2>&1; then
  sha256sum "$PACKAGE_FILE_NAME" > "$PACKAGE_FILE_NAME.sha256"
fi

echo "离线包已生成：$PACKAGE_ARCHIVE"
